name: system_design_flutter
description: "system_design_flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  storybook_flutter: ^0.14.1
  moon_design: ^1.1.0
  logger: ^2.5.0
  color_shade: ^1.0.1
  currency_formatter: ^2.2.3
  bloc: ^9.0.0
  equatable: ^2.0.7
  go_router: ^15.1.2
  flutter_skeleton_ui: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
